[0m[2023-03-01 20:42:22,341][MainThread/DEBUG] PyCqBot: Using proactor: IocpProactor[0m
[0m[2023-03-01 20:42:22,386][cqhttp_shell/ERROR] PyCqBot: go-cqhttp ·¢ÉúÖÂÃü´íÎó open cache image db failed: The process cannot access the file because it is being used by another process.[0m
